# See: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI - Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle  # Note: the 'build' task depends on many extra tasks - e.g. 'test' is also executed.
      run: ./gradlew build
